# Generated by Django 5.2.3 on 2025-06-23 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('meta_descripcion', models.CharField(blank=True, max_length=500)),
                ('palabras_clave', models.CharField(blank=True, max_length=255)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ManyToManyField(blank=True, related_name='articulos_relacionados', to='blog.categoria')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BloqueContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bloque', models.CharField(choices=[('titulo', 'Título'), ('parrafo', 'Párrafo'), ('imagen', 'Imagen'), ('lista', 'Lista'), ('codigo', 'Código'), ('otro', 'Otro')], default='parrafo', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('ruta_imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_bloques/')),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='blog.articulo')),
            ],
            options={
                'verbose_name_plural': 'Bloques de Contenido',
                'ordering': ['orden'],
            },
        ),
    ]
